services:
  - type: web
    name: travel-planner-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: supervisord -c /app/supervisord.conf
    plan: free
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: GROQ_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: RAPIDAPI_KEY
        sync: false
      - key: WEATHERAPI_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: MCP_HOST
        value: "127.0.0.1"
      - key: MCP_TRAVEL_PORT
        value: "8001"
      - key: MCP_COMMS_PORT
        value: "8002"
      - key: MCP_SEARCH_PORT
        value: "8004"
      - key: FRONTEND_URL
        sync: false
    autoDeploy: false
